_BASE_: "Base-CIS.yaml"

MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "BN"
    RES5_MULTI_GRID: [1, 1, 1]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 256
    NORM: "BN"

# 修改数据集配置为你的自定义数据集
DATASETS:
  TRAIN: ("cis_train",)
  TEST: ("cis_test",)

# 修改类别数（根据你的实际类别数量）
MODEL:
  OSFormer:
    NUM_CLASSES: 8  # 你有8个类别
  ROI_HEADS:
    NUM_CLASSES: 8  # 确保这里也是8

# 训练配置
SOLVER:
  IMS_PER_BATCH: 4        # 增加batch size到4
  BASE_LR: 0.0005         # 学习率相应调整（batch size翻倍，lr也翻倍）
  STEPS: (40000, 55000)   # 学习率衰减步骤（按5倍调整）
  MAX_ITER: 60000         # 最大迭代次数（扩大5倍）
  WARMUP_ITERS: 5000      # 预热迭代次数（按比例调整）
  CHECKPOINT_PERIOD: 5000 # 保存检查点间隔（调整保存频率）

# 输入配置
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333

# 输出目录
OUTPUT_DIR: "./output/custom_dataset"

# 测试配置
TEST:
  EVAL_PERIOD: 100000     # 设置为比MAX_ITER大的值，禁用验证

# 数据加载器配置
DATALOADER:
  NUM_WORKERS: 8          # 增加数据加载工作进程（配合更大的batch size）
  FILTER_EMPTY_ANNOTATIONS: True