# OSFormer 自定义数据集配置文件

# 基础配置
_BASE_: "Base-OSFormer.yaml"

# 模型配置
MODEL:
  META_ARCHITECTURE: "OSFormer"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"  # 预训练权重

  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"
    STEM_OUT_CHANNELS: 64
    RES5_DILATION: 2
    NORM: "FrozenBN"
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]

  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 256
    NORM: ""
    FUSE_TYPE: "sum"

  # OSFormer 特有配置
  OSFormer:
    NUM_CLASSES: 8  # 根据你的数据集修改！运行register_dataset.py后会知道确切数量
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.1
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 6
    DEC_LAYERS: 6
    PRE_NORM: False
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 1.0
    MASK_WEIGHT: 20.0
    DICE_WEIGHT: 1.0
    BBOX_WEIGHT: 5.0
    GIOU_WEIGHT: 2.0

# 数据集配置
DATASETS:
  TRAIN: ("custom_train",)
  TEST: ("custom_val",)

# 数据加载器配置
DATALOADER:
  NUM_WORKERS: 4
  ASPECT_RATIO_GROUPING: True
  FILTER_EMPTY_ANNOTATIONS: True

# 输入配置
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  MASK_FORMAT: "polygon"

# 优化器配置
SOLVER:
  IMS_PER_BATCH: 8  # 根据GPU内存调整，如果内存不足改为4或2
  BASE_LR: 1e-4
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  GAMMA: 0.1
  WARMUP_FACTOR: 1.0 / 3
  WARMUP_ITERS: 1000
  WARMUP_METHOD: "linear"
  WEIGHT_DECAY: 1e-4
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "value"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0

# 测试配置
TEST:
  EVAL_PERIOD: 5000
  DETECTIONS_PER_IMAGE: 100
  AUG:
    ENABLED: False

# 输出配置
OUTPUT_DIR: "./output_osformer"
SEED: 42

# 记录配置
VIS_PERIOD: 0
LOG_PERIOD: 50

# 检查点配置
SAVE_CHECKPOINT_PERIOD: 5000
MODEL:
  DEVICE: "cuda"  # 如果没有GPU，改为"cpu"